### PR TITLE
Ignore classes annotated with `@Generated` #28

### PR DESCRIPTION
**Pull request by Serranya**
Provide an implementation for #28.

This is a rather dirty implementation. Based on the already existing suppression filter. There is a lot of duplicated code right now and no test.

Should this PR be improved or can it be accepted as is?

Improving this PR would probably take some time. I have some ideas, but I would like to check them with you first @gaul. Maybe lets split this. Accept the PR as is and open an issue to track the cleanup and missing test.

### CODE REVIEW

**Comment by gaul** [comment]
This also needs documentation in the README.

**Comment by gaul** [comment]
This needs some kind of configuration to enable it by default and disable via a parameter.  We also need to document it in the README.

**Comment by Serranya** [comment]
@gaul I added a property to control the new behaviour. It is also documented in the README.

I also added integration tests to test the new feature. The maven-invoker-plugins builds two sample maven projects to verify that everything works as expected.

**Comment by Serranya** [comment]
@gaul Is there anything left to do to get this merged? If I can help in any way please tell me :)

**Comment by Serranya** [comment]
I added the integration test to check if my switch works. It was convenient to also test the general functionality of my change that way.

I think integration tests are a good addition to the plugin. If you don't want them I can remove them again.

**Comment by gaul** [comment]
Thank you for your contribution @Serranya!

**Comment by gaul** [comment]
When running this locally I see:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in org.gaul.modernizer_maven_plugin.GeneratedTest
itDetectsSuppressModernizerAnnotation(org.gaul.modernizer_maven_plugin.GeneratedTest)  Time elapsed: 0.047 sec  <<< FAILURE!
java.lang.AssertionError:

Actual and expected should have same size but actual size is:
 <0>
while expected is:
 <3>
Actual was:
<[]>
        at org.gaul.modernizer_maven_plugin.GeneratedTest.itDetectsSuppressModernizerAnnotation(GeneratedTest.java:37)
```

Any idea what is going on here?  This previously passed CI.

**Comment by Serranya** [comment]
Hmm my local build succeeds. Im using openjdk-8

**Comment by gaul** [comment]
@Serranya When running `mvn clean verify` I see this with 564a1012752914c5a3654f6bc057353a12112ef5 using both java-1.8.0-openjdk.x86_64 and java-11-openjdk.x86_64.

**Comment by gaul** [comment]
Sorry it appears I had some litter from an earlier iteration of this patch.  I will make a 2.0.0 release including this commit soon!

**Pull request merged**
